name: budgeteer CI/CD

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup Node.js'
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - name: yarn install, build, and test
    run: |
      yarn
      yarn test



